### ISSUE TITLE
Create a new Release

### ISSUE THREAD

**Issue by dadon-david** [sitespeedio/chrome-har#10]
Hello,

I would like to create a new release for chrome-har with the fix for initiator ( See #9 )

Do I have to make a Pull Request with a Tag and ask you to merged it so that you can create the release

Or do I have to open an Issue to create a new release ?

Thanks 😄

**Comment by tobli** [comment]
I can make a release today. How are you using chrome-har? As a library, as part of Browsertime (-> a new BT release as well), or as a part of sitespeed.io (-> new release of that)?

**Comment by dadon-david** [comment]
Awesome, I use it as a part of Browsertime :)

Thanks,

**Comment by dadon-david** [comment]
Hey @tobli,

I saw that you published a [new release](https://github.com/sitespeedio/browsertime/releases/tag/v2.3.0) of Browsertime with the updated dependency of chrome-har,

Thank you very much and thanks to the whole Sitespeed team for this amazing work,

Best,
