### ISSUE TITLE
startedDateTime attribute (for a page) is an empty string

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/chrome-har#11]
See the bug: https://github.com/sitespeedio/browsertime/issues/522

**Comment by soulgalore** [comment]
Hi @suratovvlad is there a way I can reproduce what you did to get the empty string?

**Comment by suratovvlad** [comment]
Hi @soulgalore!
I'm actively searching the steps to reproduce, however I can't find any piece of evidence and reasons...

**Comment by suratovvlad** [comment]
Oh, that's something amazing!

Could you check the logs for that sitespeed.io run? I've caught this with "-vvv" parameter.
[2018-04-05-20-51-25.zip](https://github.com/sitespeedio/chrome-har/files/1881826/2018-04-05-20-51-25.zip)
[log2.txt](https://github.com/sitespeedio/chrome-har/files/1881827/log2.txt)

We have the server located in Germany, and we are trying to test the Turkish website https://www.n11.com/arama?q=iphone+8

The parameters of this run:
`
sudo docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.3.5 --browser chrome -n 1 --plugins.remove assets,browsertime,budget,crawler,domains,graphite,metrics,pagexray,text,tracestorer,coach --plugins.add browsertime --plugins.add metrics --plugins.add tracestorer --plugins.add pagexray --no-browsertime.video --no-browsertime.speedIndex --no-browsertime.skipHar --no-browsertime.videoParams.createFilmstrip --browsertime.cacheClearRaw true --graphite.includeQueryParams true --metrics.filter "browsertime.pageSummary.statistics.timings.*" --gzipHAR true -vvv "https://www.n11.com/arama?q=iphone+8" > log2.txt`

**Comment by suratovvlad** [comment]
Wow, it seems it somehow connected with #12 ...
I'm checking other HARs and see, that NaNs appears when the "base page" is not on the first place

**Comment by soulgalore** [comment]
aha ok that's good. I did a fix for that but only for BT 3.0. I'll check for the 2.x branch to, think we need another fix for that (the different way to navigate). BTW to get the log we need, you need to pass on **--chrome.collectTracingEvents** (for 2x). 

I'll try this out later today.

**Comment by soulgalore** [comment]
I could reproduce with BT 2.x and Chrome > 65, I collected a trace and will look into it today. One thing I don't understand though is that for me it always happens with Chrome 66 or later but it seems like you get it with earlier versions.

**Comment by soulgalore** [comment]
I've made a branch with a test case that fails: https://github.com/sitespeedio/chrome-har/tree/chrome-66-bt2.x

**Comment by suratovvlad** [comment]
Yes, you are right, I get it with earlier verstions (Chrome 63, Sitespeed.io 6.3.5, Browsertime 2.1.4).
There is the output with --chrome.collectPerfLog 
[2018-04-06-07-50-21.zip](https://github.com/sitespeedio/chrome-har/files/1883150/2018-04-06-07-50-21.zip)
[log3.txt](https://github.com/sitespeedio/chrome-har/files/1883152/log3.txt)

**Comment by soulgalore** [comment]
Ah sorry since you run from sitespeed you need to run with `--browsertime.chrome.collectPerfLog` you will get a specific log file for that log, if you could attach that it would be super.

**Comment by suratovvlad** [comment]
yes, I collected with this flag already )
Do you mean this file?
[sitespeed.io.log](https://github.com/sitespeedio/chrome-har/files/1883168/sitespeed.io.log)

**Comment by soulgalore** [comment]
no, hmm seems to be a bug that Browsertime doesn't store it, if you set it through sitespeed.io. Let me see if I can reproduce it directly in BT.

**Comment by soulgalore** [comment]
Hmm no I tried with Google Chrome 63.0.3239.132 but then the main page is picked up with your example URL.

**Comment by suratovvlad** [comment]
Oh, I've caught it with Browsertime 2.1.4:
[2018-04-06T083325+0000.zip](https://github.com/sitespeedio/chrome-har/files/1883249/2018-04-06T083325.0000.zip)
The params of run:
`sudo docker run --shm-size=1g -it  -v "$(pwd)":/browsertime sitespeedio/browsertime:2.1.4  --browser chrome -n 1 --no-video --no-speedIndex --no-skipHar --no-videoParams.createFilmstrip --cacheClearRaw true --chrome.collectPerfLog true "https://www.n11.com/arama?q=iphone+8"`

**Comment by soulgalore** [comment]
ah great thanks :) ping @tobli

**Comment by tobli** [comment]
I believe this to be fixed with chrome-har 0.3.2, and Browsertime 2.5.0. Please re-open if it's not.
