### ISSUE TITLE
Early hints requests do not appear in HAR

### ISSUE THREAD

**Issue by benschwarz** [sitespeedio/chrome-har#115]
On a [page with verified early hints requests](https://www.masterofmalt.com/rum/ableforths/rumbullion-rum/) we can see requests initiated by early hints:

![image](https://github.com/sitespeedio/chrome-har/assets/924/763a8b9d-6d38-4b65-899b-7a8a72dfb0f9)

Running that page with `npx browsertime --chrome.collectPerfLog -n 1 $URL` and inspecting the HAR we can see: 

* Link headers on the main document indicating that early hint requests should be made
* **No early hints requests are present**, e.g.: no `.css` requests
* SVG requests initiated by `.css` stylesheets

Inspecting the devtools log I can see that the request made to `master-cb9e9afd3d.css` (request ID: 87395.8) has the expected `Network.requestWillBeSent`, `Network.responseReceived`, `Network.dataReceived`, `Network.loadingFinished` events.

Curiously, I noticed that both `fromDiskCache` and `fromEarlyHints` are both `true` on the `Network.responseReceived` request:

![image](https://github.com/sitespeedio/chrome-har/assets/924/68d60178-be26-45eb-a0e2-bfa325b81165)

In checking `entryFromResponse.js` we can see that `fromDiskCache` and `__servedFromCache` are used to gate functionality:

https://github.com/sitespeedio/chrome-har/blob/2006c4dce0971180b023dda3fe7c0cd085efeadf/lib/entryFromResponse.js#L93

https://github.com/sitespeedio/chrome-har/blob/2006c4dce0971180b023dda3fe7c0cd085efeadf/lib/entryFromResponse.js#L180

I suspect we'll want to check request entries to see if they've been loaded by early request hints. 

In case we need it, there's a [`Network.responseReceivedEarlyHints`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedEarlyHints) event.

**Comment by benschwarz** [comment]
It's late where I am now, I'll prepare a fix tomorrow during my day.

**Comment by soulgalore** [comment]
Thank you @benschwarz for creating the issue. Let me know If you need some help!

**Comment by soulgalore** [comment]
@benschwarz I made a PR that maybe fixes it, if you have please check if it works for you :)

**Comment by benschwarz** [comment]
Hey @soulgalore, apologies for the delay. I'll be wrapped up in something else until next week. I suspect your fix is all that's required, but I want to first check if there's any strange side effects and update the test suite so that it's covered in future.

**Comment by soulgalore** [comment]
I think that should be safe. We could add a test example, I can do that later on.
