### ISSUE TITLE
Network.responseReceivedExtraInfo may be fired before or after responseReceived.

### ISSUE THREAD

**Issue by ifduyue** [sitespeedio/chrome-har#119]
From https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo

>  responseReceivedExtraInfo may be fired before or after responseReceived.

And reading code at https://github.com/sitespeedio/chrome-har/blob/7a821bbae0e22d54c5e47714b26cb220e5a0f69b/index.js#L317-L362

Only responseReceivedExtraInfo fired after responseReceived was handled.

**Comment by ifduyue** [comment]
```
             if (params.headers) { 
               entry.response.headers = entry.response.headers.concat( 
                 parseHeaders(params.headers) 
               ); 
             } 
```

Also responseReceivedExtraInfo.headers and responseReceived.headers are almost identical, so here concat is a bug too?

**Comment by soulgalore** [comment]
Hi @ifduyue ok cool. Do you have time to make PR to fix it or do you have an example trace where it's out of order, then we can setup a test case for it so we know it's fixed?

**Comment by ifduyue** [comment]
Hi @soulgalore, OK, I'll try
