### ISSUE TITLE
Wrong base URL in Chrome 66

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/chrome-har#12]
Running on Browsertime master in Docker with Chrome 66 it seems like we miss out the base URL and that request? Running locally on my machine with Chrome 65 looks ok. Download the JSON:
http://webpagereplay-wikimedia.s3-website-us-east-1.amazonaws.com/?prefix=enwiki-test/mobile/chrome/200/Sweden/2018-03-27-13-46/

**Comment by soulgalore** [comment]
If I build in master with Chrome 66 beta it looks like this:
<img width="1137" alt="screen shot 2018-03-27 at 20 41 58" src="https://user-images.githubusercontent.com/540757/37987783-72af642c-31ff-11e8-9422-7bf30b7649ba.png">
so I'm pretty sure something changed in Chrome 66.  Let me collect a trace log and see if I can find out what.

**Comment by soulgalore** [comment]
Log example, will check more tonight: https://gist.github.com/soulgalore/2a48ff346a0dfdac101cb4fa99a3bfbc

**Comment by soulgalore** [comment]
Fixed in 0.3.1

**Comment by vlad4800** [comment]
It does not seem fixed in latest puppeteer version/chrome(1.8.0)

**Comment by soulgalore** [comment]
@vlad4800 please create an upstream bug then in puppeteer :) We use Chrome standalone for our testing with Browsertime and there it works. It seems like there are things that puppeteer do that change the trace log so it isn't the same as if you run with Chrome standalone (people have reported issues where the trace events are in the wrong order etc).

Best
Peter

**Comment by soulgalore** [comment]
No I think Puppeteer somehow changes the trace log? This project was built for https://github.com/sitespeedio/browsertime to that uses webdriver to get the trace log from Chrome. Best is to ask in the puppeteer project.
