### ISSUE TITLE
Support multiple pages navigation

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/chrome-har#29]
When we navigate to two different pages (using Browsertime) we still just create one page (branch with example trace https://github.com/sitespeedio/chrome-har/tree/multi-page-har).

The problem is that we use the frame_id as the unique key when we create a page new page. But the frame_id is the same between navigation, so when we get new requests, we match that with the first page.

**Comment by rriemann** [comment]
How is this issue linked to #19 ?

**Comment by soulgalore** [comment]
Ohh this one is old, I think we actually skipped it and create one trace per navigation that makes it so much simpler. For #19 seems to be a puppeteer issue, I don't know.
