### ISSUE TITLE
Make response.content.text full value available

### ISSUE THREAD

**Issue by mnoster** [sitespeedio/chrome-har#58]
Currently in the outputted HAR, the `response.content` object does not include the actual content, which is how the HAR typically looks when exported from the browser. Instead there is a `compression` value and no `text` value. Is there a way to enable this or implement in the code? 
```
                "response": {
                    "httpVersion": "h2",
                    "redirectURL": "",
                    "status": 200,
                    "statusText": "",
                    "content": {
                        "mimeType": "text/html",
                        "size": 1135094,
                        "compression": 979339
                    },
```

**Comment by soulgalore** [comment]
Hi @mnoster how do you create the HAR? If you use Browsertime you can enable it with:
```
 --chrome.includeResponseBodies   Include response bodies in the HAR file. [choices: "none", "all", "html"] [default: "none"
```

Best
Peter

**Comment by mnoster** [comment]
@soulgalore I am using puppeteer to launch headless chrome. I am going to try passing the `--chrome.includeResponseBodies` in the launch function.
```
    const browser = await puppeteer.launch({
        args: [
            '--incognito',
            '--window-size=1920x1080',
            '--start-fullscreen',
            '--chrome.includeResponseBodies',
        ],
    });

```

**Comment by mnoster** [comment]
@soulgalore Is there anyway to enable it with just chrome-har? The above flag does not do anything in puppeteer launch.

**Comment by soulgalore** [comment]
No that is if you run https://github.com/sitespeedio/browsertime.

If you try the instructions in the README does that work? https://github.com/sitespeedio/chrome-har#support-for-response-bodies
