### ISSUE TITLE
Advice on capturing iframe or service worker events?

### ISSUE THREAD

**Issue by sb8244** [sitespeedio/chrome-har#63]
Hi, I'm not sure of the best place to ask this. I see that there are some PRs / issues around iframe support in the project, but I'm struggling to see how to hook it up.

I am using the Chrome Extension debugger API to attach to the top level `tabId`. I then receive a top level iframe loading network event, but I won't receive any events for scripts inside of that iframe. The same thing occurs for service workers.

I think that I can manually attach to the iframe as a target, but that leaves the problem of attaching immediately and enabling network before any requests are made in the target. `Target.setAutoAttach` comes back successful, but I only see events the time *after* I restart the debugger—which is not super helpful. Using functions like `Target.setDiscoverTargets` just says "not allowed", so those don't seem viable.

Any pointers here?

**Comment by soulgalore** [comment]
Hi @sb8244 no sorry I have no idea.

**Comment by sb8244** [comment]
No problem!

My research here is that it's generally not possible because Chrome doesn't provide a way to attach early enough to a target to capture every network event. There's no documentation on it at all, but I'm seeing the target attachment fail if attached sooner than 100ms after the page starts loading. 

My current plan is to switch HAR generation tactics from the debugger to chrome devtools panel.

**Comment by sb8244** [comment]
I will close this out since there's nothing for the library here! Cheers.
