### ISSUE TITLE
Information missing from requests and responses

### ISSUE THREAD

**Issue by mikedijkstra** [sitespeedio/chrome-har#70]
I've come across an issue where headers are missing from requests and responses despite being sent by the browser.

There was an [update in Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/1592771) which introduced new protocol events that contain request information from network
service. This change introduced [Network.requestWillBeSentExtraInfo](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSentExtraInfo) and [Network.responseReceivedExtraInfo](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceivedExtraInfo) events in the devtools log.

Comparing the HAR generated by the Chrome Browser to one from `chrome-har` you can see the extra information is grouped into the request.

Using the request for a CSS file as an example, you can see in the [Devtools logs](https://gist.github.com/mikedijkstra/f10738b53866d428b4c45e227f54f399) that there is a `Network.requestWillBeSentExtraInfo` and a `Network.responseReceivedExtraInfo` but this extra information is not present in a [har generated by chrome-har](https://gist.github.com/mikedijkstra/f9776420ee9cf8c3189cb267863b07c7) while it is present in a [har generated by the chrome web inspector](https://gist.github.com/mikedijkstra/244b9324a0f63edd44d4cc183d54b238).

I'm happy to put together a PR to include this information in `chrome-har` the same way it's included by the Chrome Browser.

**Comment by soulgalore** [comment]
Hi @mikedijkstra aha cool, yes please :)
